### ISSUE TITLE
Cannot install on Mac Mojave

### ISSUE THREAD

**Issue by pistacchio** [salortiz/JsonC#4]
Hi, on MacOsx Mojave, I get the following error trying to install JsonC with `zef`:

```
===SORRY!===
Cannot load native library 'libjson-c.so.4'
```

I tried to `brew install json-c`, it installed `/usr/local/lib/libjson-c.4.dylib` but the problem is still not solve.

**EDIT**

Changing `without $Lib = NativeLibs::Loader.load('libjson-c.so.4')` to `without $Lib = NativeLibs::Loader.load('libjson-c.4.dylib')` works. I don't know what's the correct way to handle multiplatform  NativeLibs calls.

**Comment by salortiz** [comment]
Currently `NativeLibs` lacks proper support for MacOS.
In the meantime can you test using the environment variable `LIBJSON` with the following patch?

```.patch
--- a/lib/JsonC.pm6
+++ b/lib/JsonC.pm6
@@ -411,7 +411,7 @@ sub to-json(Any \v, :$pretty) is export {
 }
 
 INIT {
-    without $Lib = NativeLibs::Loader.load('libjson-c.so.4') {
+    without $Lib = NativeLibs::Loader.load(%*ENV<LIBJSON> || 'libjson-c.so.4') {
         .fail;
     }
 }
```

**Comment by pistacchio** [comment]
Hi, I can confirm that this works.

**Comment by salortiz** [comment]
@pistacchio,

I just released a new version with environment variable support and, with the help of the latest `NativesLibs`, an attempt to properlly support MacOS.

¿Can you give it a try?

**Comment by pistacchio** [comment]
Hi!
Still cannot install it. This is what I get:

```
➜  sowpods zef install JsonC
===> Searching for: JsonC
===> Updating cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
===> Updating p6c mirror: http://ecosystem-api.p6c.org/projects1.json
===> Updated p6c mirror: http://ecosystem-api.p6c.org/projects1.json
===> Updated cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
===> Searching for missing dependencies: NativeLibs:ver<0.0.5+>
===> Testing: NativeLibs:ver<0.0.5>:auth<github:salortiz>
foo.c:4:24: warning: format specifies type 'int' but the argument has type 'unsigned long' [-Wformat]
    printf("size: %d", sizeof(int));
                  ~~   ^~~~~~~~~~~
                  %lu
1 warning generated.
ld: warning: URGENT: building for OSX, but linking against dylib (/usr/lib/libpthread.dylib) built for (unknown). Note: This will be an error in the future.
ld: warning: URGENT: building for OSX, but linking against dylib (/usr/lib/libSystem.dylib) built for (unknown). Note: This will be an error in the future.
===> Testing [FAIL]: NativeLibs:ver<0.0.5>:auth<github:salortiz>
Aborting due to test failure: NativeLibs:ver<0.0.5>:auth<github:salortiz> (use --force-test to override)
```

**Comment by salortiz** [comment]
Thanks for your involvement, it is much appreciated.

That is new NativeLibs::Compile's tests failing on OSX, I should work on that.
In the meantime, can you try installing NativeLibs with --force-test:
```
zef --force-test install NativeLibs:v<0.0.5>
```
And then attempt the install of Json-C?

**Comment by pistacchio** [comment]
You're welcome, Salvador. I already tried with --force-test, as suggested by zef itself, and it worked. I think that the correct type for printing the result of `sizeof`, that is a long int, is `%zu` or `%lu` as suggested by the compiler. Have a look here: https://stackoverflow.com/questions/5943840/how-do-i-print-the-size-of-int-in-c

This should solve the problem.

Now, my main issue is that I generated a sample 134kb JSON file here https://next.json-generator.com/VylkUakDI.

I wrote this very minimal python script that basically parses it from the file 1000 time:

```python
import json

for i in range(1000):
    print(i)
    json.load(open('generated.json'))
```

On my machine this takes roughly 1.1 seconds.

The corresponding perl6 script is this:

```perl6
use JsonC;

for ^1000 {
    say $_;
    my $x = from-json 'generated.json'.IO.slurp;
}
```

And it takes 54 seconds. That's a still a lot slower than a language, Python, that is not know for being fast. I think that this kind of speed is a real stop from using the library, or perl6, in a real-world situation where JSON may be realistically much larger that 134kb and parsing them is something you happen to do hundreds of times per second (think about serializing / deserializing data to and from databases, calling REST services, serving JSON requests and so on).

I don't have any experience profiling perl6, but it would be interesting to start digging a bit and see where all the time is lost because, as per today standard, 54 milliseconds is a lot of time to parse 134kb of JSON.

**Comment by salortiz** [comment]
Just to factorize-out Perl6's IO time, can you try:
```perl6
use JsonC;

for ^1000 {
     say $_;
     my $a = JsonC::JSON.new-from-file('generated.json')
}
```

**Comment by pistacchio** [comment]
That was 2.5 sec! So, where is `JsonC::JSON.new-from-file` documented? I missed it. Is that a wrapper around some C code? Are we saying here that `.slurp()` is really slow?

```perl6
use JsonC;

for ^1000 {
    say $_;
    my $x = 'generated.json'.IO.slurp;
}
```

Takes. 1.8 seconds, so something still doesn't add up.

```python
import json

for i in range(1000):
    print(i)
    a = open('generated.json').read()
```

Still is much faster taking 0.1 seconds.

**Comment by salortiz** [comment]
`JSON` is the base class that encapsulates a json-c's `json_object`, `JSON.new-from-file` is one of its available constructors, in fact a wrapper over json-c's `json_object_from_file`.

As you see, Perl6's `.slurp()` indeed is slow, but the real performance penalty is that, at this time, creating Perl6 objects is an expensive operation because all the low level methods invocation and memory allocations involved. In particular Perl6 `Hash` and `Array` are heavy weighted ones.

The main idea behind my JsonC module is that much of that can be *delayed*, exposing json-c's structures and methods with the `JSON` class and its subclasses `JSON-P` and `JSON-A` (for JSON "arrays" and JSON "objects") to navigate and manipulate the in-memory representation, and only "unmarshal" to Perl6 objects when needed. (With the trade-off that, right  now, Perl6's `NativeCall` interfaces suffers its own overhead) 

Indeed, all this should be documented.

With the planned implementation of **JSON Pointer** (RFC 6901) for retrieving objects from a json-c object tree, I expect that some operations will be faster than with any other method.

On the other hand, the Perl6 compiler will be increasingly efficient.

Anyway, I think this issue can be closed now.

Regards

**Comment by pistacchio** [comment]
Thanks for the in-depth explanation, Salvador. I think the issue can be closed as well.
